<?xml version="1.0"?>
<package format="3">

  <name>control</name>
  <version>0.0.0</version>

  <description>WATonomous ASD A* planner</description>

  <maintainer email="your_email@example.com">
    Eric Song
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>